from argparse import ArgumentParser, REMAINDER

parser = ArgumentParser()
parser.add_argument('-l', '--logging', action='store_true')
parser.add_argument('-d', '--database', action='store_true')
parser.add_argument('-q', '--quiet', action='store_true')
parser.add_argument('-a', '--account')
parser.add_argument('-w', '--whitelist')
parser.add_argument('--pack')
parser.add_argument('--pack-data')
parser.add_argument('--unpack')
parser.add_argument('--master', action='store_true')
parser.add_argument('-s', '--script', default='', nargs='?')
parser.add_argument('args', nargs=REMAINDER)
args = vars(parser.parse_args())
